### PR TITLE
Fix `test_something` macro

### LINKED ISSUE #70: CI does not spot: libcudadevrt.lib is actually cudadevrt.lib on windows

### PR DESCRIPTION
**Pull request by musm**
Try to fix  https://github.com/JuliaGPU/CUDAapi.jl/issues/70

### CODE REVIEW

**Comment by musm** [comment]
bors try

**Comment by maleadt** [comment]
bors try
`@test_something` should have spotted this though, not sure we need another` isfile` test. Although it probably can't hurt since it's a more strict test.

**Comment by musm** [comment]
Interesting the macro doesn't seem to pick up the fact  it is `nothing`

**Comment by musm** [comment]
could we kick CI off again

**Comment by maleadt** [comment]
bors try

**Comment by musm** [comment]
So it looks like there is something with the test_something macro, since the tests now pass.

**Comment by musm** [comment]
So there's a bug in the `test_somthing` macro

Here's the fix
```
# CUDA
macro test_something(ex)
    quote
        rv = $(ex)
        @test rv != nothing
        rv
    end
end
```

**Comment by maleadt** [comment]
Ah, that's a silly mistake. Thanks for looking into this!
bors try

**Comment by musm** [comment]
Please squash this PR

**Pull request merged**
