### PR TITLE
Add `usable_cuda_gpus()` as non-noisy alternative to `has_cuda_gpu()`

### LINKED ISSUE #105: Remove warning
[This](https://github.com/JuliaGPU/CUDAapi.jl/blob/master/src/availability.jl#L53) `@warn` is creating unnecessary runtime spam for us. Can it be made an `@debug`, or removed?

Cc: @vchuravy

### PR DESCRIPTION
**Pull request by kpamnany**
Closes #105.

### CODE REVIEW

**Comment by maleadt** [comment]
Sorry, forgot about https://github.com/JuliaGPU/CUDAapi.jl/issues/105. This looks great. Alternatively, some keyword argument to `has_cuda_gpu` would have been an option too, same to me.

**Comment by maleadt** [comment]
Anyway, this just needs a test and is good to go.

**Comment by kpamnany** [comment]
I've added a test like the one for `has_cuda_gpu()`.

I also added a keyword argument to the new function to suppress output -- by default it behaves like `has_cuda_gpu()`. This is a more informative interface, so perhaps it can replace the old one eventually...?

**Comment by kpamnany** [comment]
Ugh, but I forgot to change the doc. Let me fix that.

**Comment by maleadt** [comment]
Yes, that sounds like a good plan.
bors try

**Comment by maleadt** [comment]
Travis is borked for OSX, unrelated to this PR.

**Pull request merged**
