### PR TITLE
WIP: Add CI

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Yay, all green! This should greatly improve future development.
@denizyuret @musm any comments on the way I've set-up the Windows CI?

Also, @denizyuret, I've slightly changed the behavior of `find_toolkit`/`find_driver`: these now return `nothing` instead of throwing an error when no toolkit/driver could be detected, making it possible to at least run the code and verify it executes (trapping `ErrorException` is messy and error-prone). For now, I've left `find_host_toolchain` alone (because that returns multiple values upon success).

**Comment by musm** [comment]
Awesome. So I guess 32 bit could be fixed but it's too annoying to do so without access to a 32-bit machine/not worth it for now.

**Comment by maleadt** [comment]
Well, appveyor does support 32-bit, but apparently CUDA doesn't? e.g. https://devtalk.nvidia.com/default/topic/846110/is-there-a-32-bit-version-of-cuda-7-/
So there's no real reason to test it.

**Review by musm — APPROVED** [review]

**Comment by maleadt** [comment]
Thanks for the review, @musm

EDIT: ah crap, forgot to squash.

**Pull request merged**
