### PR TITLE
 More robust and simplier detection of cl on new msvc builds

### PR DESCRIPTION
**Pull request by musm**
Using recommendations from https://github.com/Microsoft/vswhere/wiki/Find-VC 

Also if the user already has vswhere, use that, (i.e. from a `chocolatey` installation).

The previous version was super slow, from all the shelling.

### CODE REVIEW

**Comment by musm** [comment]
Unrelated, but should we drop 0.7 and  update to use the new Loggin macros instead of `@trace`

**Comment by maleadt** [comment]
`@trace` is just an additional log level.
bors try

**Comment by musm** [comment]
I'm guessing Mac buildbots are not working

**Comment by maleadt** [comment]
Yeah, unrelated to this change.

**Pull request merged**
