### PR TITLE
Don't consider all possible versions when looking for libraries

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by vchuravy** [comment]
What is the motivation behind removing the availability helpers? I have found them helpful ;)

**Comment by maleadt** [comment]
The functionality is now available through `CUDAdrv.functional()`/`CUDAnative.functional()`/`CuArrays.functional()`. But basically, I wanted to cut down on the cost of `find_cuda_library`, which now looks for all known CUDA versions. I guess I can remove that without breaking those helpers, I take it you are using them?

**Comment by maleadt** [comment]
OK, I've put them back.

**Comment by vchuravy** [comment]
I am. It let's me avoid doing `using CuArrays` if I don't have a GPU. Since that warns if it isn't functional.

**Pull request merged**
