### PR TITLE
Find cudadevrt

### PR DESCRIPTION
**Pull request by vchuravy**
Still need to figure out how the library is called on non-linux

### CODE REVIEW

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
Gah, https://github.com/JuliaWeb/MbedTLS.jl/issues/193 again. Feel free to push something like https://github.com/JuliaGPU/CUDAnative.jl/commit/58f0b6a95accbdb7a879e55dec13872c91aef1e5 here.

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
Ok to merge and tag?

**Comment by maleadt** [comment]
Yes, go ahead.

**Pull request merged**
