### PR TITLE
Filter   search directories earlier

### PR DESCRIPTION
**Pull request by musm**
Reduce required number of folders to search

### CODE REVIEW

**Comment by maleadt** [comment]
Eh, do you have a particular reason? Because otherwise you could filter `dirs` after every previous step resulting in new directories, for every discovery method; doing it only here seems pretty arbitrary.

**Comment by maleadt** [comment]
Actually, scrap that. Why did you add `dirs` to the search path of `nvcc` and `libcudart`? These rules make sure, if CUDA resides at a path that wasn't covered by the hard-coded paths or a path set via environment variables, it can still be discovered by looking backwards from the location of `nvcc` or `libcudart`. So we don't need to be looking for `nvcc` or `libcudart` in directories that are already considered as a valid toolkit path. So:

```patch
diff --git a/src/discovery.jl b/src/discovery.jl
index 7ece7d6..9e9fb10 100644
--- a/src/discovery.jl
+++ b/src/discovery.jl
@@ -181,7 +181,7 @@ function find_toolkit()
     end
     ## look for the compiler binary (in the case PATH points to the installation)
     try
-        nvcc_path = find_binary(nvcc, dirs)
+        nvcc_path = find_binary(nvcc)
         dir = dirname(nvcc_path)
         if ismatch(r"^bin(32|64)?$", basename(dir))
             dir = dirname(dir)
@@ -193,7 +193,7 @@ function find_toolkit()
     end
     ## look for the runtime library (in the case LD_LIBRARY_PATH points to the installation)
     try
-        libcudart_path = find_library(libcudart, dirs)
+        libcudart_path = find_library(libcudart)
         dir = dirname(libcudart_path)
         if ismatch(r"^(lib|bin)(32|64)?$", basename(dir))
             dir = dirname(dir)
```

No need for early filtering in that case.

**Comment by musm** [comment]
Adding `dirs` is necessary otherwise libcudart is never found since the directory where the cudatoolkit dll's and exe's are not necessarily in path (which was the case for me). By addings them, we force `dlopen.find_library` to search there first and if it can't find them in `dirs`, it'll pick them up in path.

Yeah this PR is not necessary.

**Comment by maleadt** [comment]
But that method doesn't need to find cudart, that is only done to discover additional toolkit locations.

**Comment by musm** [comment]
Let me get back to you at a later time. I'll checkout your other PR and see how things work. Thanks for help.

**Pull request closed without merging**
